USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = 'TekusDB')
BEGIN
    ALTER DATABASE TekusDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE TekusDB;
END
GO

CREATE DATABASE TekusDB;
GO

USE TekusDB;
GO